### ISSUE TITLE
AzureML workspace error - Invalid api_endpoint: https://studioapi.azureml.net

### ISSUE THREAD

**Issue by maximuslee1226** [RevolutionAnalytics/AzureML#127]
When I run the following code running in HDInsight 3.6 with R server option, I get the following error
```r
library(AzureML)
workspace <- workspace(config = "azureml-settings.json")
Error in workspace(config = "azureml-settings.json") : 
Invalid api_endpoint: https://studioapi.azureml.net
```

Even after I changed the json config file to https://ussouthcentral.stuido.azureml.net/, I still have the same error.

Please help!

**Comment by andrie** [comment]
We could probably catch the error better and display a better error message.

Doing a `readLines()` shows the root cause:

```r
> readLines("https://studioapi.azureml.net")
Error in file(con, "r") : cannot open connection
In addition: Warning message:
In file(con, "r") :
  URL 'https://studioapi.azureml.net/': status was 'Problem with the SSL CA cert (path? access rights?)'
```

And the solution is documented at the AzureDataLake blog on MSDN: ["Solving the problem of “Problem with the SSL CA cert (path? access rights?)” for R server on HDInsight"](https://blogs.msdn.microsoft.com/azuredatalake/2017/07/07/solving-the-problem-of-problem-with-the-ssl-ca-cert-path-access-rights-for-r-server-on-hdinsight/).

Try this:

```r
install.packages(c("curl", "httr"))
```

Then run your code and it should work.

**Comment by maximuslee1226** [comment]
Thank you so much Andrie,

 

That worked!

 

Thanks again,

Brandon
