### ISSUE TITLE
test-6-services-consume.R contains keys

### ISSUE THREAD

**Issue by bwlewis** [RevolutionAnalytics/azureml#32]
probably not a good idea?

**Comment by andrie** [comment]
These keys were authorised for use in testing.  The reason is that since the key doesn't include an authorisation code, you can use the key for read only, not to update the service.

@bwlewis, as you pointed out in the code comments, it is very difficult to run tests without having the key exposed in the test.

I'll re-expose the key in the code, then re-activate the test

**Comment by andrie** [comment]
On reflection, we don't need these keys exposed in the test.

We can combine `consume()` with `publishWebservice()` in the same set of tests, thus using the same set of private keys we use for the rest of the test suite.
